import QtQuick

QtObject {
    readonly property color windowBg: "#1b1b1f"
    readonly property color chromeBg: "#252528"
    readonly property color surface: "#333338"
    readonly property color surfaceHover: "#3d3d44"
    readonly property color surfaceActive: "#3a5a3c"
    readonly property color border: "#5a5a62"
    readonly property color borderAccent: "#6abf69"
    readonly property color textPrimary: "#ececec"
    readonly property color textSecondary: "#b3b3bc"
    readonly property color textMuted: "#888892"
    readonly property color accent: "#6abf69"
    readonly property color accentDark: "#3a4a3a"
    readonly property color danger: "#c62828"
    readonly property color dangerHover: "#a83232"
    readonly property color progressFill: "#4caf50"
    readonly property color warningBg: "#3a2d12"
    readonly property color warningBorder: "#8a6d2a"
    readonly property color warningText: "#ffd57a"
    readonly property color warningTextMuted: "#e6cf94"
    readonly property color warningDetail: "#a89567"
    readonly property color warningAccent: "#ffb74d"
    readonly property color infoAccent: "#5b9bd5"
}
