# Fedora 42 cloud guest
GUEST_NAME=fedora
GUEST_USER=fedora
IMAGE_URL=https://download.fedoraproject.org/pub/fedora/linux/releases/42/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-42-1.1.x86_64.qcow2
IMAGE_FILE=Fedora-Cloud-Base-Generic-42-1.1.x86_64.qcow2
PKG_FORMATS="rpm appimage"
